### ISSUE TITLE
reporter crash if easypy is launched directly as the docker run command

### ISSUE THREAD

**Issue by kecorbin** [CiscoTestAutomation/pyats-docker#1]
This does not currently work....

```
docker run -it --rm -v $(PWD):/tests ciscotestautomation/pyats easypy /tests/pyats_ios_example_job.py -testbed_file /tests/default_testbed.yaml -archive_dir=/tests/.pyATS
```

As a workaround you can do the following:

`run_tests.sh`
```
easypy /tests/pyats_ios_example_job.py -testbed_file /tests/default_testbed.yaml -archive_dir=/tests/.pyATS
```

and then 

```
docker run -it --rm -v $(PWD):/tests ciscotestautomation/pyats bash /tests/run_tests.sh
```

**Comment by siming85** [comment]
tried to replicate this on two different Mac - one with sierra and one with yosemite .. could not replicate. 
Also could not replicate with Ubuntu 14 as the host server. 

is it possible that there's some tools on your laptop/routes causing this?

**Comment by kecorbin** [comment]
I suppose anything is possible, however, that would sort of defeat the purpose of docker ;)
I'm currently running High Sierra 10.13.2
Docker version 17.09.0-ce-rc1, build ae21824

**Comment by siming85** [comment]
let me try upgrading to that and we'll see what's going on.

that rc1 though - bleeding edge my friend...

**Comment by kecorbin** [comment]
This is low priority

**Comment by siming85** [comment]
if you ever get a chance - post the whole crash screen output here.

**Comment by kecorbin** [comment]
Well.  I tried to get those logs for you, but it appears to be working today... ghost in the machine.  Closing issue.
