### ISSUE TITLE
Requirments not found ? 

### ISSUE THREAD

**Issue by automateyournetwork** [CiscoTestAutomation/pyats-docker#5]
I get the following which causes my build to fail:

RUN pip install -r /pyats/requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: '/pyats/requirements.txt'

Please advise thanks

**Comment by danielgraziano** [comment]
Hi @automateyournetwork can you please provide the steps to reproduce this issue? I am not seeing it on my end.

Are you using the pre-built image or the pyats image builder?

**Comment by automateyournetwork** [comment]
This can be closed - error on my side

**Comment by danielgraziano** [comment]
Sure no problem - thanks for notice
